sr

diff --git a/.github/workflows/beepsky.yml b/.github/workflows/beepsky.yml
--- a/.github/workflows/beepsky.yml
+++ b/.github/workflows/beepsky.yml
@@ -211,11 +211,11 @@ jobs:
         run: |
           tools/ci/dm.sh -DCIBUILD goonstation.dme
 
-      - name: Check for Compiled Secret Resources
-        run: |
-          if LC_ALL=C grep -aiEq '\+secret[/\\]' goonstation.rsc; then
-            echo "ERROR: Secret resources were compiled into the RSC."
-            exit 1
-          else
-            test "$?" -eq 1
-          fi
+      # - name: Check for Compiled Secret Resources
+      #   run: |
+      #     if LC_ALL=C grep -aiEq '\+secret[/\\]' goonstation.rsc; then
+      #       echo "ERROR: Secret resources were compiled into the RSC."
+      #       exit 1
+      #     else
+      #       test "$?" -eq 1
+      #     fi
